# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files first for dependency caching
COPY package*.json ./

# Install dependencies without running lifecycle scripts
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project and ensure the build output is generated
RUN npm run build

CMD ["npm", "start"]
